[project]
name = "mental-health-counsellor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "vllm>=0.9.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
